### ISSUE TITLE
can't run "ajv help"

### ISSUE THREAD

**Issue by cobrin** [ajv-validator/ajv-cli#102]
Running on CentOS 7.9, npm 3.10.10

```
[01:09|root@gbjhccx00:/home/admin/inventory]# npm install -g ajv-cli
/usr/bin/ajv -> /usr/lib/node_modules/ajv-cli/dist/index.js
/usr/lib
└── ajv-cli@4.0.1

[01:13|root@gbjhccx00:/home/admin/inventory]# ajv help
/usr/lib/node_modules/ajv-cli/node_modules/ajv/dist/compile/rules.js:18
        types: { ...groups, integer: true, boolean: true, null: true },
                 ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/ajv-cli/node_modules/ajv/dist/compile/validate/dataType.js:4:17)
```

Is there a syntax error in `/usr/lib/node_modules/ajv-cli/node_modules/ajv/dist/compile/rules.js` ?

```
     1  "use strict";
     2  Object.defineProperty(exports, "__esModule", { value: true });
     3  exports.getRules = exports.isJSONType = void 0;
     4  const _jsonTypes = ["string", "number", "integer", "boolean", "null", "object", "array"];
     5  const jsonTypes = new Set(_jsonTypes);
     6  function isJSONType(x) {
     7      return typeof x == "string" && jsonTypes.has(x);
     8  }
     9  exports.isJSONType = isJSONType;
    10  function getRules() {
    11      const groups = {
    12          number: { type: "number", rules: [] },
    13          string: { type: "string", rules: [] },
    14          array: { type: "array", rules: [] },
    15          object: { type: "object", rules: [] },
    16      };
    17      return {
    18          types: { ...groups, integer: true, boolean: true, null: true },
    19          rules: [{ rules: [] }, groups.number, groups.string, groups.array, groups.object],
    20          post: { rules: [] },
    21          all: { type: true, $comment: true },
    22          keywords: { type: true, $comment: true },
    23      };
    24  }
    25  exports.getRules = getRules;
    26  //# sourceMappingURL=rules.js.map
```

**Comment by epoberezkin** [comment]
Both Ajv and ajv-cli are compiled to JS 2018 target; most likely you are running an old nodejs version. 

You need to upgrade nodejs to at least v10 or to recompile to the JS version that you need to support.

**Comment by epoberezkin** [comment]
Current stable nodejs is v14 and npm is v6, npm npm v3 most likely predates nodejs v10
