### ISSUE TITLE
Error migrating from draft2019 to draft2020

### ISSUE THREAD

**Issue by mweber03** [ajv-validator/ajv-cli#125]
Using version 5.0.0, there is an error migration from draft2019 to draft2020.

my-schema.json
```
{
    "$schema": "https://json-schema.org/draft/2019-09/schema",
    "$id": "https://schema.com/my-schema.json",
    "type": "object",
    "required": [
        "number"
    ],
    "properties": {
        "number": {
            "type": "number"
        }
    }
}
```

command
```
> ajv migrate -s "my-schema.json" --spec=draft2020 --indent=4
npm\node_modules\ajv-cli\node_modules\ajv\dist\core.js:133
                throw new Error(`no schema with key or ref "${schemaKeyRef}"`);
                ^

Error: no schema with key or ref "https://json-schema.org/draft/2019-09/schema"
    at Ajv2020.validate (node_modules\ajv-cli\node_modules\ajv\dist\core.js:133:23)
    at Ajv2020.validateSchema (node_modules\ajv-cli\node_modules\ajv\dist\core.js:244:28)
    at migrateSchema (node_modules\ajv-cli\dist\commands\migrate.js:37:31)
    at Array.map (<anonymous>)
    at Object.execute (node_modules\ajv-cli\dist\commands\migrate.js:29:24)
    at Object.<anonymous> (node_modules\ajv-cli\dist\index.js:19:24)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
```

**Comment by epoberezkin** [comment]
at the moment it only supports migrating from draft-04 to any of drafts 7, 2019, 2020 - probably should be clarified in the docs.

**Comment by epoberezkin** [comment]
That’s the issue: https://github.com/ajv-validator/json-schema-migrate/issues/5#issuecomment-811881491
